### ISSUE TITLE
Use of same coefficient number for different terms in utility equation

### ISSUE THREAD

**Issue by bhargavasana** [RSGInc/DaySim#131]
In WorkTourModeModel.cs, on lines 398 and 403, coefficient number 179 is used for both origin and destination mixed use density terms in the utility. Is that intentional or a bug?

**Comment by bhargavasana** [comment]
A similar thing occurs in SchoolTourModeModel.cs on lines 306 and 307.
```
alternative.AddUtilityTerm(37, twoPersonHouseholdFlag);
alternative.AddUtilityTerm(37, onePersonHouseholdFlag);
```

**Comment by mabcal** [comment]
Those are not bugs.  Those are cases where we combined variables in estimation.  They were originally tested in estimation as separate variables and then constrained to have the same coeffcieints by setting the coefficient numbers the same.

It’s very unlikely to be a bug because the exact same code was used to estimate the models, so the application is automatically the same as the estimation – one of the very nice features of DaySim.   You can double-check that by looking at the coefficient file and make sure that there is no coefficient number near 37 that is in the coefficient file but not in the code. (In other words, the code and the coefficient file should be consistent.)

**Comment by bhargavasana** [comment]
Thanks for clarifying Mark!
